//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team_Project___GameTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameID { get; set; }
        public string GameName { get; set; }
        public string TeamOne { get; set; }
        public string TeamTwo { get; set; }
        public string TeamOneScore { get; set; }
        public string TeamTwoScore { get; set; }
        public string GameResult { get; set; }
        public System.DateTime CalendarWeek { get; set; }
    }
}
